### ISSUE TITLE
云开发的这个是啥问题

### ISSUE THREAD

**Issue by 4yeonly** [RomeoChen/movie-wechat-miniprogram#2]
[system] initCurrentClipboardData.success {errMsg: "getClipboardData:ok", data: "wxb080b88dfcb2de35"}data: "wxb080b88dfcb2de35"errMsg: "getClipboardData:ok"__proto__: Object

**Comment by RomeoChen** [comment]
没看懂额

**Comment by 4yeonly** [comment]
我也没看懂... [system] initCurrentClipboardData.success {errMsg: "getClipboardData:ok", data: 这句啥意思 都没找到这个语句

**Comment by RomeoChen** [comment]
你这句是在哪里看到的？是报错吗？

**Comment by 4yeonly** [comment]
> 你这句是在哪里看到的？是报错吗？

是报错的，能加下你微信吗，我总是传不上图来

**Comment by 4yeonly** [comment]
还是传不上图来

**Comment by 4yeonly** [comment]
我解决了 哈哈哈哈，但是现在问题是，咋添加图片

**Comment by RomeoChen** [comment]
额，其实这个项目比较久远。。。我大部分已经忘记怎么操作，依稀记得我好像没有做添加图片这个功能（

**Comment by 4yeonly** [comment]
可以加个微信吗

**Comment by 4yeonly** [comment]
发不上图来

**Comment by RomeoChen** [comment]
好，tianromeo
